### PR TITLE
Option to run a single sprinkle policy

### PR DESCRIPTION
**Pull request by artygus**
For small updates or hot fixes I pretty often do need to run a single policy, it's not very convenient to comment all the stuff or copy-paste a single policy to a new script file. This commit introduces --policy option to run a single policy, can be used together with the only role option.

### CODE REVIEW

**Comment by artygus** [comment]
@yyyc514 couldn't find any for Sprinkle::OPTIONS[:only_policy]

**Comment by artygus** [comment]
@yyyc514 just added a few tests

**Comment by yyyc514** [comment]
Cool.  What do you think about perhaps heading towards more of a subset of commands (like git) vs tons of options?

`sprinkle policy hotfix-mysql`

Any thoughts?

**Comment by artygus** [comment]
@yyyc514 sounds good, especially in the context of arguments list:
`sprinkle role app_server install.rb` or  `sprinkle roles app_server db_server install.rb`

**Comment by artygus** [comment]
@yyyc514 btw --only option acts a bit confusing to me, if a target policy has multiple roles packages will be installed for other roles too

**Comment by artygus** [comment]
@yyyc514 btw --only option behaves a bit confusing to me, if matching policies have list of roles packages will be installed for all of them, is it desired behaviour?

**Comment by artygus** [comment]
@yyyc514 crafted the draft of git-like commands in a separate branch, check this out https://github.com/artygus/sprinkle/commit/4fe0ddcbb78d4ab883d38d47fe9a88a71774420d

**Comment by artygus** [comment]
@yyyc514 is there anything wrong?

**Comment by yyyc514** [comment]
Sorry.  Not sure I like the syntax.  Feels off.

What about:

`sprinkle -s install.rb install role:app_server`

The whole existing argument system has never felt right to me.

**Comment by artygus** [comment]
@yyyc514 I think it would look better `sprinkle install role:app_server install.rb`, mm?

**Comment by yyyc514** [comment]
Actually maybe install is the wrong word... you're really executing a role/package... which might or might not install anything.  You aren't necessarily "installing" the powder file per se.  What about:

```
# installs from Powder file
sprinkle all
sprinkle role:db package:mysql
# name the file explicitely
sprinkle script.rb role:db package:mysql
```

Does anything else use the Powder name?  All the cool kids have their own files these days... Gemfile, Capfile, etc.

**Pull request closed without merging**
